context:
  # Upstream project (PyPI project name uses hyphen, sdist filename uses underscore)
  name: python-tds
  version: "1.17.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/python_tds-${{ version }}.tar.gz
  sha256: c97483a9adf1dcab8bee66e83429acc502753f389d134553edd818348b94ced0

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - pytds
      pip_check: true

about:
  homepage: https://github.com/denisenkom/pytds
  summary: "Python DBAPI driver for MSSQL using pure Python TDS (Tabular Data Stream) protocol implementation"
  description: |
    python-tds (package import name: pytds) is a pure Python implementation of the
    Tabular Data Stream (TDS) protocol providing a DB-API 2.0 compatible driver
    for Microsoft SQL Server and Sybase.
  license: MIT
  license_file: LICENSE.txt
  repository: https://github.com/denisenkom/pytds
  documentation: https://github.com/denisenkom/pytds#readme

extra:
  recipe-maintainers:
    - xylar
