{% set name = "khiops-driver-s3" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version.replace("-", "") }}

source:
  url: https://github.com/KhiopsML/khiopsdriver-s3/archive/refs/tags/{{ version }}.tar.gz
  sha256: e4290db9bf31a856bc42fca9735c7fe05f0b999f9069b3fa6864ae339bcbfcaf

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - aws-sdk-cpp
  host:
    - zlib
    - fmt
    - spdlog
  run:
    - libzlib

test:
  commands:
    - test -f $PREFIX/lib/libkhiopsdriver_file_s3.so                   # [linux]
    - test -f $PREFIX/lib/libkhiopsdriver_file_s3.dylib                # [osx]
    - if not exist %LIBRARY_BIN%/khiopsdriver_file_s3.dll exit 1       # [win]

about:
  home: https://khiops.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Khiops driver to access files on AWS S3 storage
  doc_url: https://khiops.org
  dev_url: https://github.com/khiopsml/khiopsdriver-s3

extra:
  recipe-maintainers:
    - sgouache
