{% set name = "diffhalos" %}
{% set version = "0.0.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ArgonneCPAC/diffhalos/archive/v{{ version }}.tar.gz
  sha256: 35c980a1326ca9f74bb0ae5f1e0773eb3d15b32e455f54e755aa62b06398aaf3

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python =={{ python_min }}
    - setuptools >=45
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - jax
    - diffmah

test:
  imports:
    - diffhalos
  commands:
    - pip check
  requires:
    - pip
    - python =={{ python_min }}

about:
  summary: Library for differentiable generation of halo lightcones
  home: https://github.com/ArgonneCPAC/diffhalos
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - beckermr
