{% set name = "ooi-data-explorations" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ooi_data_explorations-{{ version }}.tar.gz
  sha256: 31282b5f320b888124c0083bc91ef1ae23b356c84d915561d6ab00b46708d538

build:
  noarch: python
  script:
    - rm -rf examples/
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - xarray
    - dask-core
    - munch
    - tqdm
    - urllib3
    - numpy
    - pandas
    - gsw
    - requests
    - beautifulsoup4
    - pyyaml
    - matplotlib-base
    - ntplib
    - netcdf4
    - h5netcdf

test:
  imports:
    - ooi_data_explorations
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/oceanobservatories/ooi-data-explorations/python/
  summary: Tools for interacting with OOI data, including downloading, cleaning, and visualizing.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
