{% set version = "0.5.2" %}

package:
  name: geoarrow-rust-core-modules
  version: {{ version }}

source:
  url: https://github.com/geoarrow/geoarrow-rs/archive/refs/tags/py-v{{ version }}.tar.gz
  sha256: 9f513ce83171edd825223983fff0534e1e5c9050499ceb32d878fa97ac7add71

build:
  number: 0

outputs:
  - name: geoarrow-core
    script: build-pkg.sh  # [not win]
    script: build-pkg.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - maturin >=1.7.0,<2.0                   # [build_platform != target_platform]
        - {{ stdlib("c") }}
        - {{ compiler("c") }}
        - {{ compiler("rust") }}
        - cargo-bundle-licenses
      host:
        - python
        - maturin >=1.4.0,<2.0
        - pip
      run:
        - python
        - arro3-core >=0.4
        - pyproj
    test:
      imports:
        - geoarrow.rust.core
      commands:
        - pip check
      requires:
        - pip

  - name: geoarrow-compute
    script: build-pkg.sh  # [not win]
    script: build-pkg.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - maturin >=1.7.0,<2.0                   # [build_platform != target_platform]
        - {{ stdlib("c") }}
        - {{ compiler("c") }}
        - {{ compiler("rust") }}
        - cargo-bundle-licenses
      host:
        - python
        - maturin >=1.4.0,<2.0
        - pip
      run:
        - python
        - arro3-core >=0.4
        - pyproj
        - {{ pin_subpackage("geoarrow-rust-core", exact=True) }}
    test:
      imports:
        - geoarrow.rust.compute
      commands:
        - pip check
      requires:
        - pip

  - name: geoarrow-io
    script: build-pkg.sh  # [not win]
    script: build-pkg.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - maturin >=1.7.0,<2.0                   # [build_platform != target_platform]
        - {{ stdlib("c") }}
        - {{ compiler("c") }}
        - {{ compiler("rust") }}
        - cargo-bundle-licenses
      host:
        - python
        - maturin >=1.4.0,<2.0
        - pip
      run:
        - python
        - arro3-core >=0.4
        - pyproj
        - {{ pin_subpackage("geoarrow-rust-core", exact=True) }}
    test:
      imports:
        - geoarrow.rust.io
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/geoarrow/geoarrow-rs
  summary: Python bindings to geoarrow-rs, for using GeoArrow data in Python.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE_MIT
    - THIRDPARTY.yml
  license_url: https://github.com/geoarrow/geoarrow-rs/blob/main/LICENSE_MIT
  doc_url: https://geoarrow.org/geoarrow-rs/python
  dev_url: https://github.com/geoarrow/geoarrow-rs

extra:
  recipe-maintainers:
    - kylebarron
  feedstock-name: geoarrow-rust-core
