{% set name = "upstage-des" %}
{% set version = "0.3.3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/upstage_des-{{ version }}.tar.gz
  sha256: e7c02e320d2a6042720f511cec8f1c06f72b835f0c022927833eaf37c172ec6a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.7.1,<4
    - pip
  run:
    - python >={{ python_min }}
    - simpy >=4

test:
  imports:
    - upstage_des
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/gtri/upstage
  summary: A library for behavior-driven discrete event simulation.
  dev_url: https://github.com/gtri/upstage
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://gtri.github.io/upstage/

extra:
  recipe-maintainers:
    - JamesArruda
