schema_version: 1

context:
  name: standard-xdrlib
  version: 3.13.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/standard_xdrlib-${{ version }}.tar.gz
  sha256: 92db79aa6f1565c483a5ef73cb367a2b8b4a45130e4a2b95e96fe2c4319bcd55

build:
  number: 0
  noarch: python
  script:
    - if: build_type == "regular"
      then: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - if: build_type == "regular"
      then:
        - python 3.13.*
        - pip
        - setuptools >=75.0
  run:
    - if: build_type == "regular"
      then: python >=3.13
      else: python >=${{ python_min }},<3.13

tests:
  - if: build_type == "regular"
    then:
      - python:
          imports:
            - xdrlib
          pip_check: true
          python_version: "3.*"
    else:
      - python:
          imports:
            - xdrlib
          pip_check: true
          python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/youknowone/python-deadlib
  summary: Standard library xdrlib redistribution. "dead battery".
  license: PSF-2.0
  license_file: LICENSE
  repository: https://github.com/youknowone/python-deadlib

extra:
  recipe-maintainers:
    - beenje
