{% set name = "sasdata" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sasdata-{{ version }}.tar.gz
  sha256: 1c8a8414dd18f80e02ea817c35c235a6e06de129b2a0da001686c741c61ea672

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-requirements-txt
    - hatch-sphinx
    - hatch-vcs
    - h5py
    - lxml
    - numpy
    - pip
  run:
    - python >={{ python_min }}
    - h5py
    - lxml
    - numpy

test:
  imports:
    - sasdata
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/SasView/sasdata
  summary: Sas Data Loader application
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT

extra:
  recipe-maintainers:
    - backmari
    - mrakitin
