{% set name = "cc-qa" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cc_qa-{{ version }}.tar.gz
  sha256: 6398d1aa405d24120af7c60ba513758b80ff05a901d22da507204fd774154367

build:
  entry_points:
    - ccqa = cc_qa.run_qa:main
  noarch: python
  script:
   - rm -rf dist
   - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77.0.0
    - setuptools-scm >=6.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - cftime
    - cf_xarray
    - compliance-checker >=5.3.0
    - dask-core
    - netcdf4
    - pandas
    - xarray
    - cc-plugin-cc6 >=0.3.0

test:
  imports:
    - cc_qa
  commands:
    - pip check
    - ccqa --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://gitlab.dkrz.de/udag/cc-qa/
  summary: QA based on compliance-checker
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
