{% set name = "panic" %}
{% set version = "9.4.2" %}
{% set python_min = "3.9" %}

package:
  name: panic-suite
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/panic-{{ version }}.tar.gz
  sha256: f2772142ac60f69a8927a98317213804abb5becff565a852438288f97353827b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  # hint from cibuildwheel
  script_env:
    - MACOSX_DEPLOYMENT_TARGET=10.9

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - python
    - pip
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fandango
    - pytango

test:
  imports:
    - panic    

outputs:
  - name: panic
    build:
      entry_points:
        - PyAlarm = panic.ds.PyAlarm:main  
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - python >={{ python_min }}
        - fandango
        - pytango
      test:
        imports:
          - panic
        commands:
          - pip check
          - PyAlarm --help
        requires:
          - python {{ python_min }}  
          - pip
  # optional panic user interface, built on Taurus (PyQt5)
  - name: panic-gui
    build:
      noarch: generic
      entry_points:
        - panic = panic.gui.gui:main
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools    
      run:
        - python >={{ python_min }}
        - panic
        - taurus
      test:
        imports:
          - panic.gui
        commands:
          - pip check
          - panic --help
        requires:
          - python {{ python_min }}  
          - pip
          
about:
  home: https://gitlab.com/tango-controls/panic
  summary: PANIC, a python Alarm System for TANGO
  doc_url: https://pythonhosted.org/panic/
  license: LGPL-3.0-or-later
  license_file: LICENSE
  description: | 
    panic is a python Alarm System for TANGO Control Systems that provides
    several tools (api, Tango device server, user interface) for periodic
    evaluation of conditions, notification services, logging, automated actions
    and configuration and visualization of alarms.

extra:
  feedstock-name: panic
  recipe-maintainers:
    - sergirubio
    - ovallcorba
