{% set name = "panic" %}
{% set version = "9.4.4" %}
{% set python_min = "3.11" %}

package:
  name: panic
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/panic-{{ version }}.tar.gz
  sha256: 70a035f7618680a6bbf64dcaa56c3d25de510137eccd9fc89b1763dc65148cad
  
build:
  number: 0
  skip: true

requirements:
  build:
    - python
    - pip
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fandango
    - pytango

test:
  imports:
    - panic    

outputs:
  - name: panic-server
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      entry_points:
        - PyAlarm = panic.ds.PyAlarm:main
        - panic = panic.gui.gui:main        
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - python >={{ python_min }}
        - fandango
        - pytango
      test:
        imports:
          - panic.ds
        commands:
          - pip check
          - PyAlarm --help
        requires:
          - python {{ python_min }}  
          - pip
  # optional panic user interface, built on Taurus (PyQt5)
  - name: panic-gui
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('panic-server', exact=True) }}
        - taurus-qt
      test:
        imports:
          - panic.gui
        commands:
          - panic --help
          
about:
  home: https://gitlab.com/tango-controls/panic
  summary: PANIC, a python Alarm System for TANGO
  doc_url: https://pythonhosted.org/panic/
  license: LGPL-3.0-or-later
  license_file: LICENSE
  description: | 
    panic is a python Alarm System for TANGO Control Systems that provides
    several tools (api, Tango device server, user interface) for periodic
    evaluation of conditions, notification services, logging, automated actions
    and configuration and visualization of alarms.

extra:
  feedstock-name: panic
  recipe-maintainers:
    - sergirubio
    - ovallcorba
