{% set name = "panic" %}
{% set version = "9.4.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/panic-{{ version }}.tar.gz
  sha256: f2772142ac60f69a8927a98317213804abb5becff565a852438288f97353827b

build:
  noarch: python {{ python_min }}
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - panic = panic.gui.gui:main
    - PyAlarm = panic.ds.PyAlarm:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fandango
    - pytango
    - taurus    

test:
  imports:
    - panic
  commands:
    - pip check
    - PyAlarm --help
  requires:
    - python >={{ python_min }}  
    - pip
    - fandango
    - pytango

about:
  home: https://gitlab.com/tango-controls/panic
  summary: PANIC, a python Alarm System for TANGO
  doc_url: https://pythonhosted.org/panic/
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sergirubio
