context:
  name: ufit
  version: 1.11.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ufit-${{ version }}.tar.gz
  sha256: b68f4976991bc2464ac631be43d93e34921fc38ea520a7e1eff27a3c4196cc68

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - ufitgui=ufit.gui:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }} 
    - matplotlib-base >=3.0
    - numpy
    - scipy
    - pyqt
    - lmfit

tests:
  - python:
      imports:
        - ufit
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
    script:
      - ufitgui --help

about:
  summary: Universal scattering data fitting tool
  license: BSD-2-Clause
  license_file: LICENSE
  repository: https://forge.frm2.tum.de/review/plugins/gitiles/mlz/general/ufit
  homepage: https://pythonhosted.org/ufit/

extra:
  recipe-maintainers:
    - MridulS
