{% set python_min = "3.12" %}
{% set name = "seabirdfilehandler" %}
{% set version = "0.7.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/seabirdfilehandler-{{ version }}.tar.gz
  sha256: 17f2bc93607d7d0fb51ab64ef81f45f754c34f4e6e1b8b851e1855d23c1ea909

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=2.2.1
    - xmltodict >=0.13.0

test:
  imports:
    - seabirdfilehandler
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://ctd-software.pages.io-warnemuende.de/seabirdfilehandler
  summary: Library of parsers to interact with SeaBird CTD files.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
