{% set name = "metadata-crawler" %}
{% set version = "2509.0.0" %}
{% set python_min = 3.11 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/metadata_crawler-{{ version }}.tar.gz
  sha256: 18a4e2c4a2b6f4fd7bb9b7d72a963ad5c038fa8fe4f356790488f11442156aea

build:
  entry_points:
    - metadata-crawler = metadata_crawler.cli:cli
    - mdc = metadata_crawler.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2
    - pip
  run:
    - python {{ python_min }}
    - aiohttp
    - appdirs
    - anyio
    - ciso8601
    - fsspec
    - diskcache
    - s3fs
    - jinja2
    - intake
    - intake-xarray
    - intake-esm
    - pandas
    - python-dateutil
    - numpy
    - orjson
    - pyarrow
    - h5netcdf
    - pydantic
    - rich
    - rich-argparse
    - tomli
    - tomlkit
    - typing_extensions
    - zarr
    - xarray
    - httpx
    - uvloop
    - motor

test:
  imports:
    - metadata_crawler
  commands:
    - pip check
    - metadata-crawler --help
    - mdc --help
  requires:
    - pip

about:
  summary: Crawl, extract and push climate metadata for indexing.
  dev_url: https://github.com/freva-org/metadata-crawler
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - antarcticrainforest
