---
cxx_compiler:
  - gxx # [linux]
  - clangxx # [osx]
  - vs2022 # [win]
cxx_compiler_version:
  - 12 # [linux]
  - 16 # [osx]

c_stdlib_version:          # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.15"                # [osx and x86_64]