---
c_compiler:
  - gcc # [linux]
  - clang # [osx]
  - vs2022 # [win]
c_compiler_version:
  - 12 # [linux]
  - 16 # [osx]
cxx_compiler:
  - gxx # [linux]
  - clangxx # [osx]
  - vs2022 # [win]
cxx_compiler_version:
  - 12 # [linux]
  - 16 # [osx]
