{% set version = "0.0.11".replace("-", "") %}
package:
  name: khiops-driver-gcs
  version: {{ version }}

source:
  url: https://github.com/KhiopsML/khiopsdriver-gcs/releases/download/{{ version }}/khiops-driver-gcs.tar.gz
  sha256: 75c5b38224a48c33afe4ec5833f38661f81456aa1aa30285beb282a450682f62

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - libgoogle-cloud-storage-devel
    - libboost-devel
    - libboost-headers
  host:
    - fmt
    - spdlog

    - libgoogle-cloud-storage
    - libgoogle-cloud

files:
  - lib/libkhiopsdriver_file_gcs.so*         # [linux]
  - lib/libkhiopsdriver_file_gcs*.dylib      # [osx]
  - lib/*.dll                                # [win]
  - bin/*.dll                                # [win]

test:
  commands:
    - test -f $PREFIX/lib/libkhiopsdriver_file_gcs.so                   # [linux]
    - test -f $PREFIX/lib/libkhiopsdriver_file_gcs.{{ version }}.dylib  # [osx]
    - if not exist %LIBRARY_BIN%/khiopsdriver_file_gcs.dll exit 1       # [win]

about:
  home: https://khiops.org
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Khiops driver to access files on Google Cloud Storage
  doc_url: https://khiops.org
  dev_url: https://github.com/khiopsml/khiopsdriver_gcs

extra:
  recipe-maintainers:
    - sgouache
    - bruno-at-orange
