{% set name = "khiops-driver-gcs" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version.replace("-", "") }}

source:
  url: https://github.com/KhiopsML/khiopsdriver-gcs/archive/refs/tags/{{ version }}.tar.gz
  sha256: 456daa8f441bf2e461b73949c87307dd7f20ed1e62c4a334a6d4dbcf094cc713

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - libgoogle-cloud-storage-devel
    - libboost-devel
    - libboost-headers
  host:
    - fmt
    - spdlog
    - libabseil >=20250127.*                 # [win]
    - libgoogle-cloud-storage
    - libgoogle-cloud
    - libcurl                                # [win]
    - libcrc32c                              # [win]


#files:
#  - lib/libkhiopsdriver_file_gcs.so*         # [linux]
#  - lib/libkhiopsdriver_file_gcs*.dylib      # [osx]
#  - lib/*.dll                                # [win]

test:
  commands:
    - test -f $PREFIX/lib/libkhiopsdriver_file_gcs.so                   # [linux]
    - test -f $PREFIX/lib/libkhiopsdriver_file_gcs.dylib                # [osx]
    - if not exist %LIBRARY_BIN%/khiopsdriver_file_gcs.dll exit 1       # [win]

about:
  home: https://khiops.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Khiops driver to access files on Google Cloud Storage
  doc_url: https://khiops.org
  dev_url: https://github.com/khiopsml/khiopsdriver_gcs

extra:
  recipe-maintainers:
    - sgouache
