context:
  version: "0.0.12"

package:
  name: khiops-driver-gcs
  version: ${{ version }}

source:
  url: https://github.com/KhiopsML/khiopsdriver-gcs/archive/refs/tags/${{ version }}.tar.gz
  sha256: 456daa8f441bf2e461b73949c87307dd7f20ed1e62c4a334a6d4dbcf094cc713

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - fmt
    - spdlog
    - zlib
    - libgoogle-cloud-storage-devel
    - libboost-devel
    - libboost-headers
    - libcrc32c
    - if: win
      then: libcurl

tests:
  - script:
    - if: unix
      then: test -f $PREFIX/lib/libkhiopsdriver_file_gcs${SHLIB_EXT}
      else: 
        - if not exist %LIBRARY_PREFIX%\bin\libkhiopsdriver_file_gcs.dll exit 1 

about:
  homepage: https://khiops.org
  license: BSD-3-Clause-Clear
  license_file: LICENSE
  summary: Khiops driver to access files on Google Cloud Storage
  description: The GCS driver plugin extends Khiops to enable processing of data files located on Google Cloud Storage

extra:
  recipe-maintainers:
    - sgouache
