{% set name = "syncup" %}
{% set version = "0.1.0" %}
{% set python_min = "3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/syncup-{{ version }}.tar.gz
  sha256: b5157d161c7f02a7ee5395ba39dc4b0e0a270fee7dc50415ea5fe7acc8e88845

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >={{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - syncup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/clintval/syncup
  summary: Synchronizers for lazy iterators.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - clintval
