context:
  name: mdbtools
  version: "1.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ name }}/${{ name }}/releases/download/v${{ version }}/${{ name }}-${{ version }}.tar.gz
  sha256: "ff9c425a88bc20bf9318a332eec50b17e77896eef65a0e69415ccb4e396d1812"

build:
  number: 0
  skip:
    - win
  script:
    content: |
      autoreconf -fis -I "${BUILD_PREFIX}/share/gettext/m4"
      ./configure --prefix="${PREFIX}"
      make -j"${CPU_COUNT}"
      make install

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - autoconf
    - automake
    - gawk
    - gettext
    - libiconv
    - libtool
    - make
    - pkg-config
    - which

tests:
  - package_contents:
      bin:
        - mdb-export
        - mdb-schema
  - script:
    - mdb-export --help
    - mdb-schema --help

about:
  homepage: https://github.com/mdbtools/mdbtools
  summary: 'MDB Tools - Read Access databases on *nix'
  description: |
    Welcome to the exciting world of MDB Tools! MDB Tools is a set of programs
    to help you extract data from Microsoft Access files in various settings.
    See the NEWS file for information about the latest release.
  license: GPL-2.0-only
  license_file:
    - COPYING
  documentation: https://github.com/mdbtools/mdbtools/blob/master/README.md
  repository: https://github.com/mdbtools/mdbtools

extra:
  recipe-maintainers:
    - JulianWachterQC
    - moritzwilksch
