{% set name = "madoka" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/madoka-{{ version }}.tar.gz
  sha256: e258baa84fc0a3764365993b8bf5e1b065383a6ca8c9f862fb3e3e709843fae7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - madoka
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ikegami-yukino/madoka-python
  summary: Memory-efficient CountMin Sketch key-value structure (based on Madoka C++ library)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
