{% set name = "django-admin-numeric-filter" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_admin_numeric_filter-{{ version }}.tar.gz
  sha256: 22985bee625a08f76671e88647bfec0e04f2363e747bf26fad03603d4e32f0f1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry >=1.0
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - django >=3.2

test:
  imports:
    - admin_numeric_filter
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/lukasvinclav/django-admin-numeric-filter
  summary: Numeric filters for Django admin
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Maarten-vd-Sande
